import Link from 'next/link';
import '../styles/globals.scss';
import { Inter } from 'next/font/google';
import NavigationBar from '../components/NavigationBar';

const inter = Inter({ subsets: ['latin'], });

// ${inter.className} // removed this from the main class

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="night">
      <head>
        <link href="https://fonts.cdnfonts.com/css/cera-round-pro" rel="stylesheet"></link>
      </head>

      <body className={`app flex flex-col max-h-screen`}>
      {/* bg-base-200 */}
        <NavigationBar /> 

        <main className='app-wrapper'>
          {children}
        </main>

        <Footer />
      </body>
    </html>
  )
}

function Footer(props) {
  return (
    <div className='h-12 bg-base-100'>footer</div>
  )
}