import '../styles/globals.scss';
import { Inter } from 'next/font/google';

import { Navbar } from "@/components/Navbar/Navbar";

import { Application } from "@/app/ApplicationContext";

import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: [ 'latin' ], });

export const metadata = {
  title: 'Create Next App', description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="dark">
    <body className={`${inter.className} flex flex-col h-screen max-h-screen `}>
    <Application>
      <Toaster/>
      <Navbar/>
      <div className="app-wrapper h-full">{children}</div>
    </Application>
    </body>
    </html>
  )
}