import './globals.scss';

import { Inter } from 'next/font/google';
const inter = Inter({ subsets: [ 'latin' ], });
import { Application } from "@/app/ApplicationContext";
import Navbar from "@/components/Navbar/Navbar";



export const metadata = {
  title: 'Create Next App', description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="night" >
      <body className={`${inter.className} flex flex-col`}>
      <Application>
        <Navbar />
        {children}
      </Application>
      </body>
    </html>
  )
}