import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import Providers from "@/app/(context)/serverProviders";
import "../styles/globals.scss";
import NavBar from "@/components/ui/navBar";
import {Toaster} from "react-hot-toast";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}>
        <Providers>
            <div className="flex flex-col h-screen">
                <NavBar/>
                <main className="flex flex-col flex-1 min-h-0">
                    {children}
                </main>
            </div>
            <Toaster position="bottom-right"/>
        </Providers>
        </body>
        </html>
    );
}
